version: 2

workflows:
  version: 2
  build-calc:
    jobs:
      - checkout_code
      - set_permissions:
          requires: [checkout_code]
      - install_dependencies:
          requires: [set_permissions]
      - build:
          requires: [install_dependencies]

#############################################################
# Shared jobs and configuration
#############################################################

attach_workspace: &attach_workspace
  attach_workspace:
    at: '.'

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: '.'
    paths: [ '.' ]

#############################################################
# build jobs
#############################################################
jobs:
  checkout_code:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - *persist_workspace

  set_permissions:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - *persist_workspace
  
  install_dependencies:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: pip install -r requirements.txt
      - *persist_workspace

  build:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: make build
 




