version: 2

#############################################################
# Workflows
#############################################################
workflows:
  version: 2
  build-calc:
    jobs:
      - checkout_code
      - install_dependencies:
          requires: [checkout_code]
      - unit_tests:
          requires: [install_dependencies]
      - build:
          requires: [unit_tests]

#############################################################
# Shared jobs and configuration
#############################################################

attach_workspace: &attach_workspace
  attach_workspace:
    at: '.'

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: '.'
    paths: [ '.' ]

#############################################################
# build jobs
#############################################################
jobs:
  checkout_code:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - *persist_workspace

  install_dependencies:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: pip install -r requirements.txt -t .lib/
      - *persist_workspace

  unit_tests:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: make test
      - *persist_workspace

  build:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - *attach_workspace
      - run: make build
 




