version: 2

jobs:
  build:
    working_directory: ~/calc
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            pip install -r requirements.txt
            make test
            mkdir test_results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test_results
          destination: tr1
